//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailAnalyzer.Models.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytic
    {
        public int Id { get; set; }
        public int ExpertId { get; set; }
        public int DomainId { get; set; }
        public string Keyword { get; set; }
        public int NumberOfOccurrence { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Domain Domain { get; set; }
    }
}
