//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailAnalyzer.Models.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string MailFrom { get; set; }
        public string SenderName { get; set; }
        public string MailTo { get; set; }
        public string ReceiptName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime MsgDate { get; set; }
    }
}
