//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailAnalyzer.Models.DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<Expert> Experts { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<SubDomain> SubDomains { get; set; }
        public virtual DbSet<Analytic> Analytics { get; set; }
    }
}
