//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailAnalyzer.Models.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubDomain
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string Name { get; set; }
        public Nullable<int> DomainId { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
